version: '2'

services:
  mongo:
    image: mongo
    container_name: mongo-db
    volumes:
      - ./mongo/data/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - "27017:27017"
